[package]
name = "squire-compile"
version = "0.1.0"
authors = ["Sam Westerman <mail@sampersand.me>"]
edition = "2018"

[dependencies]
squire-runtime = { path = "../squire-runtime" }
tracing = "0.1.26"
